#!/bin/csh

#
# Generated by basicFT2.com Version 2024.061.14.35
#
# basicFT2.com -in test.fid -out test.ft2 -xEXTX1 3% \
#              -xEXTXN 47% -xP0 -50.0 -yFTARG alt 

nmrPipe -in test.fid \
| nmrPipe -fn SP -off 0.5 -end 0.95 -pow 2 -elb 0.0 -glb 0.0 -c 0.5 \
| nmrPipe -fn FT -verb \
| nmrPipe -fn PS -p0 -50.0 -p1 0.0 -di \
| nmrPipe -fn EXT -x1 3% -xn 47% -sw \
| nmrPipe -fn TP \
| nmrPipe -fn SP -off 0.5 -end 0.98 -pow 10 -elb 0.0 -glb 0.0 -c 0.5 \
| nmrPipe -fn TP \
  -out test.ft2 -ov
