#!/bin/csh

#
# Generated by basicFT2.com Version 2024.061.14.35
#
# basicFT2.com -in test.fid -out test.ft2 -xEXTX1 3% \
#              -xEXTXN 47% -xP0 -50.0 -yFTARG alt 

nmrPipe -in GB1_recon.ft2\
| nmrPipe -fn SOL \
| nmrPipe -fn TP \
| nmrPipe -fn FT -alt -verb \
| nmrPipe -fn PS -p0 0.0 -p1 0.0 -di \
| nmrPipe -fn TP \
| nmrPipe -fn POLY -auto -verb \
  -out test.ft2 -ov
